/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as CloudSigninRouteImport } from './routes/cloud-signin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUdharRouteImport } from './routes/_authenticated/udhar'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedMonthlyRouteImport } from './routes/_authenticated/monthly'
import { Route as AuthenticatedGheeRouteImport } from './routes/_authenticated/ghee'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCashCounterRouteImport } from './routes/_authenticated/cash-counter'
import { Route as AuthenticatedUdharIndexRouteImport } from './routes/_authenticated/udhar.index'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases.index'
import { Route as AuthenticatedMonthlyIndexRouteImport } from './routes/_authenticated/monthly.index'
import { Route as AuthenticatedUdharCustomerIdRouteImport } from './routes/_authenticated/udhar.$customerId'
import { Route as AuthenticatedSuppliersSupplierIdRouteImport } from './routes/_authenticated/suppliers.$supplierId'
import { Route as AuthenticatedReportsSummaryRouteImport } from './routes/_authenticated/reports.summary'
import { Route as AuthenticatedPurchasesSuppliersRouteImport } from './routes/_authenticated/purchases.suppliers'
import { Route as AuthenticatedPurchasesSupplierIdRouteImport } from './routes/_authenticated/purchases.$supplierId'
import { Route as AuthenticatedMonthlyDeliveriesRouteImport } from './routes/_authenticated/monthly.deliveries'
import { Route as AuthenticatedMonthlyClientIdRouteImport } from './routes/_authenticated/monthly.$clientId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudSigninRoute = CloudSigninRouteImport.update({
  id: '/cloud-signin',
  path: '/cloud-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUdharRoute = AuthenticatedUdharRouteImport.update({
  id: '/udhar',
  path: '/udhar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonthlyRoute = AuthenticatedMonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGheeRoute = AuthenticatedGheeRouteImport.update({
  id: '/ghee',
  path: '/ghee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashCounterRoute =
  AuthenticatedCashCounterRouteImport.update({
    id: '/cash-counter',
    path: '/cash-counter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUdharIndexRoute = AuthenticatedUdharIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUdharRoute,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuppliersRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPurchasesRoute,
  } as any)
const AuthenticatedMonthlyIndexRoute =
  AuthenticatedMonthlyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMonthlyRoute,
  } as any)
const AuthenticatedUdharCustomerIdRoute =
  AuthenticatedUdharCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedUdharRoute,
  } as any)
const AuthenticatedSuppliersSupplierIdRoute =
  AuthenticatedSuppliersSupplierIdRouteImport.update({
    id: '/$supplierId',
    path: '/$supplierId',
    getParentRoute: () => AuthenticatedSuppliersRoute,
  } as any)
const AuthenticatedReportsSummaryRoute =
  AuthenticatedReportsSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedPurchasesSuppliersRoute =
  AuthenticatedPurchasesSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedPurchasesRoute,
  } as any)
const AuthenticatedPurchasesSupplierIdRoute =
  AuthenticatedPurchasesSupplierIdRouteImport.update({
    id: '/$supplierId',
    path: '/$supplierId',
    getParentRoute: () => AuthenticatedPurchasesRoute,
  } as any)
const AuthenticatedMonthlyDeliveriesRoute =
  AuthenticatedMonthlyDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedMonthlyRoute,
  } as any)
const AuthenticatedMonthlyClientIdRoute =
  AuthenticatedMonthlyClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedMonthlyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cloud-signin': typeof CloudSigninRoute
  '/setup': typeof SetupRoute
  '/cash-counter': typeof AuthenticatedCashCounterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ghee': typeof AuthenticatedGheeRoute
  '/monthly': typeof AuthenticatedMonthlyRouteWithChildren
  '/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRouteWithChildren
  '/udhar': typeof AuthenticatedUdharRouteWithChildren
  '/monthly/$clientId': typeof AuthenticatedMonthlyClientIdRoute
  '/monthly/deliveries': typeof AuthenticatedMonthlyDeliveriesRoute
  '/purchases/$supplierId': typeof AuthenticatedPurchasesSupplierIdRoute
  '/purchases/suppliers': typeof AuthenticatedPurchasesSuppliersRoute
  '/reports/summary': typeof AuthenticatedReportsSummaryRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/udhar/$customerId': typeof AuthenticatedUdharCustomerIdRoute
  '/monthly/': typeof AuthenticatedMonthlyIndexRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/udhar/': typeof AuthenticatedUdharIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cloud-signin': typeof CloudSigninRoute
  '/setup': typeof SetupRoute
  '/cash-counter': typeof AuthenticatedCashCounterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ghee': typeof AuthenticatedGheeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/monthly/$clientId': typeof AuthenticatedMonthlyClientIdRoute
  '/monthly/deliveries': typeof AuthenticatedMonthlyDeliveriesRoute
  '/purchases/$supplierId': typeof AuthenticatedPurchasesSupplierIdRoute
  '/purchases/suppliers': typeof AuthenticatedPurchasesSuppliersRoute
  '/reports/summary': typeof AuthenticatedReportsSummaryRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/udhar/$customerId': typeof AuthenticatedUdharCustomerIdRoute
  '/monthly': typeof AuthenticatedMonthlyIndexRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/udhar': typeof AuthenticatedUdharIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cloud-signin': typeof CloudSigninRoute
  '/setup': typeof SetupRoute
  '/_authenticated/cash-counter': typeof AuthenticatedCashCounterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ghee': typeof AuthenticatedGheeRoute
  '/_authenticated/monthly': typeof AuthenticatedMonthlyRouteWithChildren
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRouteWithChildren
  '/_authenticated/udhar': typeof AuthenticatedUdharRouteWithChildren
  '/_authenticated/monthly/$clientId': typeof AuthenticatedMonthlyClientIdRoute
  '/_authenticated/monthly/deliveries': typeof AuthenticatedMonthlyDeliveriesRoute
  '/_authenticated/purchases/$supplierId': typeof AuthenticatedPurchasesSupplierIdRoute
  '/_authenticated/purchases/suppliers': typeof AuthenticatedPurchasesSuppliersRoute
  '/_authenticated/reports/summary': typeof AuthenticatedReportsSummaryRoute
  '/_authenticated/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/_authenticated/udhar/$customerId': typeof AuthenticatedUdharCustomerIdRoute
  '/_authenticated/monthly/': typeof AuthenticatedMonthlyIndexRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/_authenticated/udhar/': typeof AuthenticatedUdharIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cloud-signin'
    | '/setup'
    | '/cash-counter'
    | '/dashboard'
    | '/ghee'
    | '/monthly'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/udhar'
    | '/monthly/$clientId'
    | '/monthly/deliveries'
    | '/purchases/$supplierId'
    | '/purchases/suppliers'
    | '/reports/summary'
    | '/suppliers/$supplierId'
    | '/udhar/$customerId'
    | '/monthly/'
    | '/purchases/'
    | '/reports/'
    | '/suppliers/'
    | '/udhar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cloud-signin'
    | '/setup'
    | '/cash-counter'
    | '/dashboard'
    | '/ghee'
    | '/settings'
    | '/monthly/$clientId'
    | '/monthly/deliveries'
    | '/purchases/$supplierId'
    | '/purchases/suppliers'
    | '/reports/summary'
    | '/suppliers/$supplierId'
    | '/udhar/$customerId'
    | '/monthly'
    | '/purchases'
    | '/reports'
    | '/suppliers'
    | '/udhar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cloud-signin'
    | '/setup'
    | '/_authenticated/cash-counter'
    | '/_authenticated/dashboard'
    | '/_authenticated/ghee'
    | '/_authenticated/monthly'
    | '/_authenticated/purchases'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/udhar'
    | '/_authenticated/monthly/$clientId'
    | '/_authenticated/monthly/deliveries'
    | '/_authenticated/purchases/$supplierId'
    | '/_authenticated/purchases/suppliers'
    | '/_authenticated/reports/summary'
    | '/_authenticated/suppliers/$supplierId'
    | '/_authenticated/udhar/$customerId'
    | '/_authenticated/monthly/'
    | '/_authenticated/purchases/'
    | '/_authenticated/reports/'
    | '/_authenticated/suppliers/'
    | '/_authenticated/udhar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CloudSigninRoute: typeof CloudSigninRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-signin': {
      id: '/cloud-signin'
      path: '/cloud-signin'
      fullPath: '/cloud-signin'
      preLoaderRoute: typeof CloudSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/udhar': {
      id: '/_authenticated/udhar'
      path: '/udhar'
      fullPath: '/udhar'
      preLoaderRoute: typeof AuthenticatedUdharRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monthly': {
      id: '/_authenticated/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof AuthenticatedMonthlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ghee': {
      id: '/_authenticated/ghee'
      path: '/ghee'
      fullPath: '/ghee'
      preLoaderRoute: typeof AuthenticatedGheeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-counter': {
      id: '/_authenticated/cash-counter'
      path: '/cash-counter'
      fullPath: '/cash-counter'
      preLoaderRoute: typeof AuthenticatedCashCounterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/udhar/': {
      id: '/_authenticated/udhar/'
      path: '/'
      fullPath: '/udhar/'
      preLoaderRoute: typeof AuthenticatedUdharIndexRouteImport
      parentRoute: typeof AuthenticatedUdharRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedSuppliersRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedPurchasesRoute
    }
    '/_authenticated/monthly/': {
      id: '/_authenticated/monthly/'
      path: '/'
      fullPath: '/monthly/'
      preLoaderRoute: typeof AuthenticatedMonthlyIndexRouteImport
      parentRoute: typeof AuthenticatedMonthlyRoute
    }
    '/_authenticated/udhar/$customerId': {
      id: '/_authenticated/udhar/$customerId'
      path: '/$customerId'
      fullPath: '/udhar/$customerId'
      preLoaderRoute: typeof AuthenticatedUdharCustomerIdRouteImport
      parentRoute: typeof AuthenticatedUdharRoute
    }
    '/_authenticated/suppliers/$supplierId': {
      id: '/_authenticated/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AuthenticatedSuppliersSupplierIdRouteImport
      parentRoute: typeof AuthenticatedSuppliersRoute
    }
    '/_authenticated/reports/summary': {
      id: '/_authenticated/reports/summary'
      path: '/summary'
      fullPath: '/reports/summary'
      preLoaderRoute: typeof AuthenticatedReportsSummaryRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/purchases/suppliers': {
      id: '/_authenticated/purchases/suppliers'
      path: '/suppliers'
      fullPath: '/purchases/suppliers'
      preLoaderRoute: typeof AuthenticatedPurchasesSuppliersRouteImport
      parentRoute: typeof AuthenticatedPurchasesRoute
    }
    '/_authenticated/purchases/$supplierId': {
      id: '/_authenticated/purchases/$supplierId'
      path: '/$supplierId'
      fullPath: '/purchases/$supplierId'
      preLoaderRoute: typeof AuthenticatedPurchasesSupplierIdRouteImport
      parentRoute: typeof AuthenticatedPurchasesRoute
    }
    '/_authenticated/monthly/deliveries': {
      id: '/_authenticated/monthly/deliveries'
      path: '/deliveries'
      fullPath: '/monthly/deliveries'
      preLoaderRoute: typeof AuthenticatedMonthlyDeliveriesRouteImport
      parentRoute: typeof AuthenticatedMonthlyRoute
    }
    '/_authenticated/monthly/$clientId': {
      id: '/_authenticated/monthly/$clientId'
      path: '/$clientId'
      fullPath: '/monthly/$clientId'
      preLoaderRoute: typeof AuthenticatedMonthlyClientIdRouteImport
      parentRoute: typeof AuthenticatedMonthlyRoute
    }
  }
}

interface AuthenticatedMonthlyRouteChildren {
  AuthenticatedMonthlyClientIdRoute: typeof AuthenticatedMonthlyClientIdRoute
  AuthenticatedMonthlyDeliveriesRoute: typeof AuthenticatedMonthlyDeliveriesRoute
  AuthenticatedMonthlyIndexRoute: typeof AuthenticatedMonthlyIndexRoute
}

const AuthenticatedMonthlyRouteChildren: AuthenticatedMonthlyRouteChildren = {
  AuthenticatedMonthlyClientIdRoute: AuthenticatedMonthlyClientIdRoute,
  AuthenticatedMonthlyDeliveriesRoute: AuthenticatedMonthlyDeliveriesRoute,
  AuthenticatedMonthlyIndexRoute: AuthenticatedMonthlyIndexRoute,
}

const AuthenticatedMonthlyRouteWithChildren =
  AuthenticatedMonthlyRoute._addFileChildren(AuthenticatedMonthlyRouteChildren)

interface AuthenticatedPurchasesRouteChildren {
  AuthenticatedPurchasesSupplierIdRoute: typeof AuthenticatedPurchasesSupplierIdRoute
  AuthenticatedPurchasesSuppliersRoute: typeof AuthenticatedPurchasesSuppliersRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
}

const AuthenticatedPurchasesRouteChildren: AuthenticatedPurchasesRouteChildren =
  {
    AuthenticatedPurchasesSupplierIdRoute:
      AuthenticatedPurchasesSupplierIdRoute,
    AuthenticatedPurchasesSuppliersRoute: AuthenticatedPurchasesSuppliersRoute,
    AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
  }

const AuthenticatedPurchasesRouteWithChildren =
  AuthenticatedPurchasesRoute._addFileChildren(
    AuthenticatedPurchasesRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsSummaryRoute: typeof AuthenticatedReportsSummaryRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsSummaryRoute: AuthenticatedReportsSummaryRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedSuppliersRouteChildren {
  AuthenticatedSuppliersSupplierIdRoute: typeof AuthenticatedSuppliersSupplierIdRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
}

const AuthenticatedSuppliersRouteChildren: AuthenticatedSuppliersRouteChildren =
  {
    AuthenticatedSuppliersSupplierIdRoute:
      AuthenticatedSuppliersSupplierIdRoute,
    AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
  }

const AuthenticatedSuppliersRouteWithChildren =
  AuthenticatedSuppliersRoute._addFileChildren(
    AuthenticatedSuppliersRouteChildren,
  )

interface AuthenticatedUdharRouteChildren {
  AuthenticatedUdharCustomerIdRoute: typeof AuthenticatedUdharCustomerIdRoute
  AuthenticatedUdharIndexRoute: typeof AuthenticatedUdharIndexRoute
}

const AuthenticatedUdharRouteChildren: AuthenticatedUdharRouteChildren = {
  AuthenticatedUdharCustomerIdRoute: AuthenticatedUdharCustomerIdRoute,
  AuthenticatedUdharIndexRoute: AuthenticatedUdharIndexRoute,
}

const AuthenticatedUdharRouteWithChildren =
  AuthenticatedUdharRoute._addFileChildren(AuthenticatedUdharRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCashCounterRoute: typeof AuthenticatedCashCounterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGheeRoute: typeof AuthenticatedGheeRoute
  AuthenticatedMonthlyRoute: typeof AuthenticatedMonthlyRouteWithChildren
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRouteWithChildren
  AuthenticatedUdharRoute: typeof AuthenticatedUdharRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCashCounterRoute: AuthenticatedCashCounterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGheeRoute: AuthenticatedGheeRoute,
  AuthenticatedMonthlyRoute: AuthenticatedMonthlyRouteWithChildren,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRouteWithChildren,
  AuthenticatedUdharRoute: AuthenticatedUdharRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CloudSigninRoute: CloudSigninRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
